"""
Pytest configuration and shared fixtures for ap-copy-lights tests.

Generated By: Cursor (Claude Sonnet 4.5)
"""

import pytest
import shutil
from pathlib import Path


@pytest.fixture
def tmp_path(request):
    """
    Custom tmp_path fixture that uses workspace directory to avoid permission issues.
    """
    # Use workspace directory for temp files to avoid sandbox permission issues
    workspace_root = Path(__file__).parent.parent
    test_tmp_dir = workspace_root / ".test_tmp"
    test_tmp_dir.mkdir(exist_ok=True)

    # Create a unique subdirectory for this test
    import uuid

    test_dir = test_tmp_dir / f"test_{uuid.uuid4().hex[:8]}"
    test_dir.mkdir(exist_ok=True)

    yield test_dir

    # Cleanup
    try:
        shutil.rmtree(test_dir, ignore_errors=True)
    except Exception:
        pass
