"""
Generated By: Cursor (Claude Sonnet 4.5)

This script moves LIGHT files from a source directory to a destination directory,
organizing them based on FITS header metadata into a multi-stage workflow.
"""

import argparse
import os
from pathlib import Path
import re

import ap_common
from . import config


def move_files(
    source_dir: str,
    dest_dir: str,
    debug: bool = False,
    dryrun: bool = False,
    blink_dir: str | None = None,
    accept_dir: str | None = None,
    create_accept: bool = True,
) -> None:
    """
    Moves LIGHT files from source_dir to dest_dir, organizing them based on FITS header metadata.

    Args:
        source_dir: Source directory containing raw LIGHT files
        dest_dir: Destination directory for organized files
        debug: Enable debug output
        dryrun: Perform dry run without actually moving files
        blink_dir: Directory name for LIGHT files (default: "10_Blink")
        accept_dir: Directory name for accept subdirectories (default: "accept")
        create_accept: Whether to create accept subdirectories (default: True)
    """
    input_pattern = config.INPUT_PATTERN_ALL

    # Use provided directory names or defaults from config
    blink_directory = blink_dir if blink_dir is not None else config.DIRECTORY_BLINK
    accept_directory = accept_dir if accept_dir is not None else config.DIRECTORY_ACCEPT

    # Required properties for LIGHT files
    required_properties = [
        "camera",
        "type",
        "date",
        "exposureseconds",
        "datetime",
        "filename",
        "optic",
        "focal_ratio",
        "filter",
        "targetname",
    ]

    # Get metadata for LIGHT files (recursive search, show status)
    data = ap_common.get_filtered_metadata(
        dirs=[source_dir],
        patterns=[input_pattern],
        recursive=True,
        required_properties=required_properties,
        filters={"type": "LIGHT"},
        debug=debug,
        profileFromPath=False,
        printStatus=True,
    )

    print("Moving LIGHT files..", end=".", flush=True)

    # Collect all "target" directories (parent of DATE) so can create "accept" sub-dirs
    target_dirs = set()
    count_files = 0

    for datum in data.values():
        filename_src = datum["filename"]

        if "type" not in datum:
            print(f"WARNING: type not set in datum, skipping: {datum}")
            continue

        # Determine destination filename based on metadata (using BLINK directory)
        filename_dest = ap_common.normalize_filename(
            output_directory=dest_dir,
            input_filename=filename_src,
            headers=datum,
            statedir=blink_directory,
        )

        # Move the file
        ap_common.copy_file(
            from_file=filename_src,
            to_file=filename_dest,
            debug=debug,
            dryrun=dryrun,
        )

        count_files += 1
        if count_files % 50 == 0:
            print(".", end="", flush=True)

        # Create accept directories for target directories
        if create_accept:
            for t in re.findall("(.*)[\\\\\\/]DATE.*", filename_dest):
                if t not in target_dirs and not dryrun:
                    # Create the accept directory as we go, more idempotent overall (resilient to failures)
                    Path(t + os.sep + accept_directory).mkdir(
                        parents=True, exist_ok=True
                    )
                target_dirs.add(t)

    print(f"\nMoved {count_files} LIGHT file(s)")

    # Clean up empty directories in source
    print("Cleaning up empty directories...")
    ap_common.delete_empty_directories(source_dir, dryrun=dryrun)


def main() -> None:
    """Main entry point for the command-line interface."""
    parser = argparse.ArgumentParser(
        description="Move LIGHT files from source directory to destination directory"
    )
    parser.add_argument(
        "source_dir", type=str, help="Source directory containing raw files"
    )
    parser.add_argument(
        "dest_dir", type=str, help="Destination directory for organized files"
    )
    parser.add_argument("--debug", action="store_true", help="Enable debug output")
    parser.add_argument(
        "--dryrun", action="store_true", help="Perform dry run without moving files"
    )
    parser.add_argument(
        "--blink-dir",
        type=str,
        default=None,
        help='Directory name for LIGHT files (default: "10_Blink")',
    )
    parser.add_argument(
        "--accept-dir",
        type=str,
        default=None,
        help='Directory name for accept subdirectories (default: "accept")',
    )
    parser.add_argument(
        "--no-accept",
        action="store_true",
        help="Do not create accept subdirectories",
    )

    args = parser.parse_args()

    move_files(
        source_dir=args.source_dir,
        dest_dir=args.dest_dir,
        debug=args.debug,
        dryrun=args.dryrun,
        blink_dir=args.blink_dir,
        accept_dir=args.accept_dir,
        create_accept=not args.no_accept,
    )


if __name__ == "__main__":
    main()
